spring:
  #连接数据库
  datasource:
    url: jdbc:mysql://localhost:3306/vue-springboot?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  #jap
  jap:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  #热部署
  devtools:
    restart:
      enabled: true
